import { requireAuth } from '../middleware/auth.js';
import { Router, type Request, type Response } from "express";
import { createClient } from "../utils/supabase.js";
import {
  getServiceToken,
  getSaKey,
  getGoogleTokenFromEnv,
  fetchT,
  logAudit,
  logEmail,
  sendWhatsApp,
  sendGmailRaw,
  getAlertPhoneNumber,
  getServiceClient,
  callAI,
  callAIJSON,
  base64url,
  authenticateRequest,
  enqueueFailedJob,
  TONY_EMAIL,
  JANUS_EMAIL,
  MOM_EMAIL,
  EMME_EMAIL,
  ISLA_EMAIL,
  HOME_LAT,
  HOME_LNG,
  type ServiceAccountKey,
} from "../lib/helpers.js";

import {
  fetchGoogleCurrentConditions,
  fetchGoogleHourlyForecast,
  googleConditionToDescription as googleCondToDescription,
  googleConditionToEmoji as googleCondToEmoji,
} from '../utils/google-weather.js';
import {
  buildWeatherSourceData,
  extractWeatherData,
  fetchMarketSnapshot,
  fetchOpenMeteoWeather,
  formatWeatherForAI,
  type MarketItem,
  type MarketSnapshot,
  type WeatherSourceData,
} from "../services/morningReportData.js";

const router = Router();

const SECTION_MARKERS = [
  "EXECUTIVE SUMMARY",
  "INTRODUCTION",
  "FINDINGS & ANALYSIS",
  "RECOMMENDATIONS & NEXT STEPS",
  "SOURCES",
];

const BRAND_DARK = { red: 0.13, green: 0.13, blue: 0.13 };
const BRAND_GRAY = { red: 0.45, green: 0.45, blue: 0.45 };

function formatDate(): string {
  const d = new Date();
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

async function createFormattedGoogleDoc(
  projectName: string,
  reportBody: string,
  teamMembers: string,
  token: string,
): Promise<{ docId: string; docUrl: string }> {
  const createRes = await fetch("https://docs.googleapis.com/v1/documents", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: `${projectName} — Assembled Report`,
    }),
  });
  if (!createRes.ok)
    throw new Error(`Doc create failed: ${await createRes.text()}`);
  const doc = await createRes.json();
  const docId = doc.documentId;
  const docUrl = `https://docs.google.com/document/d/${docId}`;

  const dateStr = formatDate();
  const headerBlock = [
    "CLUB 34",
    "",
    projectName,
    "",
    dateStr,
    `Prepared by: ${teamMembers}`,
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
  ].join("\n");

  const footerBlock = [
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "Generated by Janus | Club 34",
    "This report was automatically assembled from project artifacts.",
  ].join("\n");

  const fullText = headerBlock + reportBody + footerBlock;

  const insertRequests: any[] = [
    { insertText: { location: { index: 1 }, text: fullText } },
  ];

  await fetch(
    `https://docs.googleapis.com/v1/documents/${docId}:batchUpdate`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ requests: insertRequests }),
    },
  );

  const formatRequests: any[] = [];
  const base = 1;

  const club34End = base + "CLUB 34".length;
  formatRequests.push({
    updateTextStyle: {
      range: { startIndex: base, endIndex: club34End },
      textStyle: {
        bold: true,
        fontSize: { magnitude: 10, unit: "PT" },
        foregroundColor: { color: { rgbColor: BRAND_GRAY } },
        smallCaps: true,
      },
      fields: "bold,fontSize,foregroundColor,smallCaps",
    },
  });

  const titleStart = base + headerBlock.indexOf(projectName);
  const titleEnd = titleStart + projectName.length;
  formatRequests.push(
    {
      updateParagraphStyle: {
        range: { startIndex: titleStart, endIndex: titleEnd + 1 },
        paragraphStyle: { namedStyleType: "HEADING_1" },
        fields: "namedStyleType",
      },
    },
    {
      updateTextStyle: {
        range: { startIndex: titleStart, endIndex: titleEnd },
        textStyle: {
          bold: true,
          fontSize: { magnitude: 24, unit: "PT" },
          foregroundColor: { color: { rgbColor: BRAND_DARK } },
        },
        fields: "bold,fontSize,foregroundColor",
      },
    },
  );

  const bodyStart = base + headerBlock.length;
  const bodyEnd = base + headerBlock.length + reportBody.length;
  formatRequests.push({
    updateTextStyle: {
      range: { startIndex: bodyStart, endIndex: bodyEnd },
      textStyle: {
        fontSize: { magnitude: 11, unit: "PT" },
        foregroundColor: { color: { rgbColor: BRAND_DARK } },
      },
      fields: "fontSize,foregroundColor",
    },
  });

  for (const marker of SECTION_MARKERS) {
    const markerIdx = fullText.indexOf(marker);
    if (markerIdx === -1) continue;
    const mStart = base + markerIdx;
    const mEnd = mStart + marker.length;
    formatRequests.push(
      {
        updateParagraphStyle: {
          range: { startIndex: mStart, endIndex: mEnd + 1 },
          paragraphStyle: { namedStyleType: "HEADING_2" },
          fields: "namedStyleType",
        },
      },
      {
        updateTextStyle: {
          range: { startIndex: mStart, endIndex: mEnd },
          textStyle: {
            bold: true,
            fontSize: { magnitude: 14, unit: "PT" },
            foregroundColor: { color: { rgbColor: BRAND_DARK } },
          },
          fields: "bold,fontSize,foregroundColor",
        },
      },
    );
  }

  if (formatRequests.length > 0) {
    await fetch(
      `https://docs.googleapis.com/v1/documents/${docId}:batchUpdate`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ requests: formatRequests }),
      },
    );
  }

  return { docId, docUrl };
}

async function shareDocWithUser(
  docId: string,
  email: string,
  token: string,
): Promise<void> {
  try {
    await fetch(
      `https://www.googleapis.com/drive/v3/files/${docId}/permissions?sendNotificationEmail=false`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          type: "user",
          role: "writer",
          emailAddress: email,
        }),
      },
    );
  } catch (e) {
    console.error(`Share error for ${email}:`, e);
  }
}

router.post("/assemble", async (req: Request, res: Response) => {
  try {
    const { project_id } = req.body;
    if (!project_id)
      return res.status(400).json({ error: "project_id is required" });

    const authUser = (req as any).user;
    if (!authUser) return res.status(401).json({ error: "Unauthorized" });

    const svc = getServiceClient();
    const user = { id: authUser.userId, email: authUser.email || "" };
    const userEmail = user.email;

    const { data: project } = await svc
      .from("janus_projects")
      .select("name, notion_page_id")
      .eq("id", project_id)
      .single();
    const projectName = (project as any)?.name || "Untitled Project";

    const { data: userProfile } = await svc
      .from("profiles")
      .select("display_name")
      .eq("user_id", user.id)
      .single();
    const requesterName =
      (userProfile as any)?.display_name || userEmail;

    const { data: shares } = await svc
      .from("janus_project_shares")
      .select("shared_with_user_id")
      .eq("project_id", project_id);

    const sharedUserIds = (shares || []).map(
      (s: any) => s.shared_with_user_id,
    );
    const teamNames: string[] = [requesterName];
    const participantEmails: string[] = [];
    if (userEmail) participantEmails.push(userEmail);

    if (sharedUserIds.length > 0) {
      const { data: sharedProfiles } = await svc
        .from("profiles")
        .select("user_id, display_name")
        .in("user_id", sharedUserIds);

      for (const uid of sharedUserIds) {
        const profile = (sharedProfiles || []).find(
          (p: any) => p.user_id === uid,
        );
        const {
          data: { user: sharedUser },
        } = await svc.auth.admin.getUserById(uid);
        if (sharedUser?.email && sharedUser.email !== userEmail)
          participantEmails.push(sharedUser.email);
        if (
          profile?.display_name &&
          !teamNames.includes(profile.display_name)
        )
          teamNames.push(profile.display_name);
      }
    }

    const teamMembers = teamNames.join(", ");

    const { data: artifacts, error: artErr } = await svc
      .from("janus_project_artifacts")
      .select("*")
      .eq("project_id", project_id)
      .order("sort_order", { ascending: true });
    if (artErr) throw new Error(`Failed to fetch artifacts: ${artErr.message}`);
    if (!artifacts || artifacts.length === 0)
      throw new Error("No artifacts to assemble");

    const artifactText = artifacts
      .map((a: any, i: number) => {
        const header = `Artifact ${i + 1}: ${a.title} (type: ${a.artifact_type})`;
        const content =
          a.artifact_type === "image"
            ? `[Image: ${a.content.startsWith("data:") ? "base64 image" : a.content}]`
            : a.content;
        return `${header}\n${content}`;
      })
      .join("\n\n---\n\n");

    const systemPrompt = `You are a professional report writer. You will receive project artifacts from a project called "${projectName}".

Your job is to organize them into a well-structured professional report. Output PLAIN TEXT ONLY — do NOT use any markdown formatting. Use these exact section headers:

EXECUTIVE SUMMARY
INTRODUCTION
FINDINGS & ANALYSIS
RECOMMENDATIONS & NEXT STEPS
SOURCES

Rules:
- Write in a professional, clear tone
- Preserve all factual content
- Use line breaks and spacing to separate ideas
- Do not include base64 image data — just note "[Image attached in artifacts]"
- Keep paragraphs concise`;

    const report = await callAI(systemPrompt, artifactText);

    const token = await getServiceToken(
      getSaKey(),
      [
        "https://www.googleapis.com/auth/documents",
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/gmail.send",
      ].join(" "),
      JANUS_EMAIL,
    );

    const { docId, docUrl } = await createFormattedGoogleDoc(
      projectName,
      report,
      teamMembers,
      token,
    );

    for (const email of participantEmails) {
      await shareDocWithUser(docId, email, token);
    }

    const docTitle = `${projectName} — Assembled Report`;
    for (const email of participantEmails) {
      try {
        const emailHtml = `<!DOCTYPE html><html><body style="font-family:system-ui,sans-serif;background:#f8f9fa;padding:40px 0;">
<div style="max-width:520px;margin:0 auto;background:#fff;border-radius:12px;padding:32px;box-shadow:0 2px 8px rgba(0,0,0,0.06);">
  <h2 style="margin:0 0 8px;font-size:20px;color:#111;">📄 Report Assembled</h2>
  <p style="color:#555;font-size:15px;line-height:1.5;">
    The assembled report for <strong>${projectName}</strong> is ready.
  </p>
  <a href="${docUrl}" target="_blank" style="display:inline-block;margin:20px 0;padding:12px 24px;background:#111;color:#fff;border-radius:8px;text-decoration:none;font-size:14px;font-weight:600;">
    Open Google Doc →
  </a>
  <p style="color:#999;font-size:12px;margin-top:16px;">Sent by Janus · Club 34</p>
</div></body></html>`;
        const enc = new TextEncoder();
        const boundary = `b_${crypto.randomUUID().replace(/-/g, "")}`;
        const mime = [
          `From: Janus <${JANUS_EMAIL}>`,
          `To: ${email}`,
          `Subject: ${docTitle}`,
          `MIME-Version: 1.0`,
          `Content-Type: multipart/alternative; boundary="${boundary}"`,
          ``,
          `--${boundary}`,
          `Content-Type: text/plain; charset="UTF-8"`,
          ``,
          `Your assembled report is ready: ${docUrl}`,
          ``,
          `--${boundary}`,
          `Content-Type: text/html; charset="UTF-8"`,
          ``,
          emailHtml,
          ``,
          `--${boundary}--`,
        ].join("\r\n");

        const raw = base64url(enc.encode(mime));
        await fetch(
          "https://gmail.googleapis.com/gmail/v1/users/me/messages/send",
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${token}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ raw }),
          },
        );
        await logEmail(
          "assembly_report",
          docTitle,
          [email],
          `Report: ${docUrl}`,
          "sent",
        );
      } catch (emailErr: any) {
        console.error(`Email to ${email} failed:`, emailErr);
        await logEmail(
          "assembly_report",
          docTitle,
          [email],
          `Report: ${docUrl}`,
          "error",
          emailErr.message,
        );
      }
    }

    try {
      const notionPageId = (project as any)?.notion_page_id;
      if (notionPageId) {
        const notionKey = process.env.NOTION_API_KEY;
        if (notionKey) {
          await fetch("https://api.notion.com/v1/comments", {
            method: "POST",
            headers: {
              Authorization: `Bearer ${notionKey}`,
              "Notion-Version": "2022-06-28",
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              parent: { page_id: notionPageId },
              rich_text: [
                {
                  text: {
                    content:
                      `📄 Report assembled: ${docTitle}\n\n${docUrl}`.slice(
                        0,
                        2000,
                      ),
                  },
                },
              ],
            }),
          });
        }
      }
    } catch (_) {}

    return res.json({ success: true, doc_url: docUrl });
  } catch (e) {
    console.error("assemble-report error:", e);
    return res.status(500).json({
      error: e instanceof Error ? e.message : "Unknown error",
    });
  }
});

// CT #129 (2026-05-17): meeting-prep-briefing retired permanently — disabled
// 2026-05-11, deleted now. Past audit rows remain. The `meeting_prep_dedup`
// table is intentionally left in place (no destructive migration). To restore
// the feature, recover from git history at commit prior to this change.
router.post("/meeting-prep", async (_req: Request, res: Response) => {
  return res.status(410).json({
    ok: false,
    error: "meeting-prep retired (CT #129)",
  });
});


function getLAOffset(forDate?: Date): string {
  const d = forDate || new Date();
  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone: "America/Los_Angeles",
    timeZoneName: "shortOffset",
  });
  const parts = formatter.formatToParts(d);
  const tzPart = parts.find((p) => p.type === "timeZoneName");
  if (tzPart?.value) {
    const match = tzPart.value.match(/GMT([+-]?\d+)/);
    if (match) {
      const hours = parseInt(match[1], 10);
      const sign = hours <= 0 ? "-" : "+";
      return `${sign}${String(Math.abs(hours)).padStart(2, "0")}:00`;
    }
  }
  return "-08:00";
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

async function fetchTodaysCalendar(
  saKey: ServiceAccountKey,
  email: string,
  label: string,
): Promise<string> {
  try {
    const token = await getServiceToken(
      saKey,
      "https://www.googleapis.com/auth/calendar.readonly",
      email,
    );
    const now = new Date();
    const laDate = now.toLocaleDateString("en-CA", {
      timeZone: "America/Los_Angeles",
    });
    const offset = getLAOffset();
    const timeMin = `${laDate}T00:00:00${offset}`;
    const timeMax = `${laDate}T23:59:59${offset}`;
    const url = `https://www.googleapis.com/calendar/v3/calendars/${email}/events?timeMin=${encodeURIComponent(timeMin)}&timeMax=${encodeURIComponent(timeMax)}&singleEvents=true&orderBy=startTime&maxResults=25`;
    const r = await fetchT(url, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!r.ok) return `(Failed to fetch ${label} calendar)`;
    const data = await r.json();
    if (!data.items?.length) return "No events today.";
    return data.items
      .map((e: any) => {
        const time = e.start?.dateTime
          ? new Date(e.start.dateTime).toLocaleTimeString("en-US", {
              hour: "numeric",
              minute: "2-digit",
              timeZone: "America/Los_Angeles",
            })
          : "All day";
        return `• ${time} — ${e.summary || "Busy"}`;
      })
      .join("\n");
  } catch (_) {
    return `(Calendar fetch error for ${label})`;
  }
}

async function fetchTomorrowsCalendar(
  saKey: ServiceAccountKey,
): Promise<string> {
  try {
    const token = await getServiceToken(
      saKey,
      "https://www.googleapis.com/auth/calendar.readonly",
      TONY_EMAIL,
    );
    const now = new Date();
    const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
    const laDate = tomorrow.toLocaleDateString("en-CA", {
      timeZone: "America/Los_Angeles",
    });
    const offset = getLAOffset(tomorrow);
    const timeMin = `${laDate}T00:00:00${offset}`;
    const timeMax = `${laDate}T23:59:59${offset}`;
    const url = `https://www.googleapis.com/calendar/v3/calendars/${TONY_EMAIL}/events?timeMin=${encodeURIComponent(timeMin)}&timeMax=${encodeURIComponent(timeMax)}&singleEvents=true&orderBy=startTime&maxResults=25`;
    const r = await fetchT(url, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!r.ok) return "(Failed to fetch)";
    const data = await r.json();
    if (!data.items?.length) return "No events tomorrow.";
    return data.items
      .map((e: any) => {
        const time = e.start?.dateTime
          ? new Date(e.start.dateTime).toLocaleTimeString("en-US", {
              hour: "numeric",
              minute: "2-digit",
              timeZone: "America/Los_Angeles",
            })
          : "All day";
        return `• ${time} — ${e.summary || "Busy"}`;
      })
      .join("\n");
  } catch (_) {
    return "(Calendar error)";
  }
}

async function generateSummary(context: string): Promise<string> {
  return callAI(
    `You are Janus, the household's AI chief of staff. Write a concise, professional end-of-day summary email. Use a warm but efficient tone. Format as clean HTML for email (no markdown). Include brief sections for: Today's Highlights, Tomorrow Preview, Action Items. Keep under 400 words.`,
    context,
    3000,
  );
}

router.post("/eod-summary", requireAuth, async (_req: Request, res: Response) => {
  const t0 = Date.now();
  try {
    const { query: dbQuery } = await import('../lib/db.js');
    const laDate = new Date().toLocaleDateString("en-CA", {
      timeZone: "America/Los_Angeles",
    });
    try {
      await dbQuery(
        `INSERT INTO report_email_dedup (report_type, period_key)
         VALUES ($1, $2)`,
        ['eod-summary', laDate],
      );
    } catch (dedupErr: unknown) {
      if (typeof dedupErr === 'object' && dedupErr !== null && (dedupErr as { code?: string }).code === '23505') {
        console.log(`[eod-summary] Skipping duplicate — already sent for ${laDate}`);
        return res.json({ ok: true, skipped: true, reason: 'already_sent_today', period: laDate });
      }
      throw dedupErr;
    }

    const saKey = getSaKey();
    const svc = getServiceClient();

    const dateStr = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
      timeZone: "America/Los_Angeles",
    });

    const [todayCal, tomorrowCal] = await Promise.all([
      fetchTodaysCalendar(saKey, TONY_EMAIL, "Tony"),
      fetchTomorrowsCalendar(saKey),
    ]);

    const { data: auditActions } = await svc
      .from("system_audit_log")
      .select("summary, edge_function, created_at")
      .gte("created_at", `${laDate}T00:00:00`)
      .not("channel", "eq", "cron")
      .order("created_at", { ascending: false })
      .limit(15);
    const actions = (auditActions || [])
      .map(
        (a: any) =>
          `• [${a.edge_function}] ${a.summary}`,
      )
      .join("\n") || "No notable actions today.";

    const { data: automationLogs } = await svc
      .from("family_automation_logs")
      .select("status, output, error_message")
      .gte("started_at", `${laDate}T00:00:00`)
      .limit(10);
    const automations = (automationLogs || [])
      .map(
        (a: any) =>
          `• ${a.status}: ${JSON.stringify(a.output || a.error_message || "").slice(0, 100)}`,
      )
      .join("\n") || "No automations ran today.";

    const { data: overdueReminders } = await svc
      .from("janus_reminders")
      .select("reminder_text,due_at")
      .is("fired_at", null)
      .lte("due_at", new Date().toISOString())
      .limit(10);
    const tasks = (overdueReminders || [])
      .map(
        (r: any) =>
          `• ${r.reminder_text} (due ${r.due_at})`,
      )
      .join("\n") || "No overdue tasks.";

    const { data: pendingReminders } = await svc
      .from("janus_reminders")
      .select("reminder_text,due_at")
      .is("fired_at", null)
      .gt("due_at", new Date().toISOString())
      .order("due_at", { ascending: true })
      .limit(5);
    const reminders = (pendingReminders || [])
      .map(
        (r: any) =>
          `• ${r.reminder_text} (${r.due_at})`,
      )
      .join("\n") || "No pending reminders.";

    const rawContext = [
      `End of Day Household Summary`,
      `Date: ${dateStr}`,
      "",
      "TODAY'S CALENDAR:",
      todayCal,
      "",
      "TOMORROW'S CALENDAR:",
      tomorrowCal,
      "",
      "USER ACTIONS TODAY:",
      actions,
      "",
      "AUTOMATION RESULTS:",
      automations,
      "",
      "OVERDUE / DUE TASKS:",
      tasks,
      "",
      "PENDING REMINDERS:",
      reminders,
    ].join("\n");

    const summary = await generateSummary(rawContext);

    const subject = `End of Day — ${dateStr}`;
    const sent = await sendGmailRaw(
      saKey,
      TONY_EMAIL,
      subject,
      summary,
      rawContext,
    );

    await sendWhatsApp(
      `EOD summary sent to your email. ${tasks.includes("•") ? "You have overdue tasks." : "All clear on tasks."}`,
    );

    logAudit("daily-eod-summary", {
      category: "automation",
      event_type: "eod_summary",
      severity: "info",
      actor_id: "system",
      actor_name: "Janus",
      channel: "cron",
      summary: `EOD summary sent${sent ? "" : " (email failed)"}`,
      status: sent ? "success" : "partial",
      duration_ms: Date.now() - t0,
    });

    return res.json({
      ok: true,
      email_sent: sent,
      duration_ms: Date.now() - t0,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : "unknown";
    logAudit("daily-eod-summary", {
      category: "automation",
      event_type: "eod_summary_error",
      severity: "error",
      actor_id: "system",
      channel: "cron",
      summary: `EOD summary error: ${msg.slice(0, 100)}`,
      status: "error",
    });
    await enqueueFailedJob("daily-eod-summary", e);
    return res.status(500).json({ ok: false, error: msg });
  }
});

function getThisWeekMondayLA(): string {
  const now = new Date();
  const laDate = new Date(
    now.toLocaleString("en-US", { timeZone: "America/Los_Angeles" }),
  );
  const day = laDate.getDay();
  const diffToMonday = day === 0 ? -6 : 1 - day;
  laDate.setDate(laDate.getDate() + diffToMonday);
  return laDate.toLocaleDateString("en-CA", {
    timeZone: "America/Los_Angeles",
  });
}

function getNextWeekRange(): { monday: string; friday: string } {
  const now = new Date();
  const laDate = new Date(
    now.toLocaleString("en-US", { timeZone: "America/Los_Angeles" }),
  );
  const day = laDate.getDay();
  const daysToNextMonday = day === 0 ? 1 : 8 - day;
  const nextMon = new Date(laDate);
  nextMon.setDate(laDate.getDate() + daysToNextMonday);
  const nextFri = new Date(nextMon);
  nextFri.setDate(nextMon.getDate() + 4);
  return {
    monday: nextMon.toLocaleDateString("en-CA"),
    friday: nextFri.toLocaleDateString("en-CA"),
  };
}

router.post("/weekly-planning", requireAuth, async (_req: Request, res: Response) => {
  const t0 = Date.now();
  try {
    const { query: dbQuery } = await import('../lib/db.js');
    const { monday, friday } = getNextWeekRange();
    const weekPeriodKey = monday;
    try {
      await dbQuery(
        `INSERT INTO report_email_dedup (report_type, period_key)
         VALUES ($1, $2)`,
        ['weekly-planning', weekPeriodKey],
      );
    } catch (dedupErr: unknown) {
      if (typeof dedupErr === 'object' && dedupErr !== null && (dedupErr as { code?: string }).code === '23505') {
        console.log(`[weekly-planning] Skipping duplicate — already sent for week of ${weekPeriodKey}`);
        return res.json({ ok: true, skipped: true, reason: 'already_sent_this_week', period: weekPeriodKey });
      }
      throw dedupErr;
    }

    const saKey = getSaKey();
    const svc = getServiceClient();

    const dateStr = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
      timeZone: "America/Los_Angeles",
    });
    const nextWeekLabel = `${new Date(monday + "T12:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric" })} – ${new Date(friday + "T12:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric" })}`;

    const calToken = await getServiceToken(
      saKey,
      "https://www.googleapis.com/auth/calendar.readonly",
      TONY_EMAIL,
    );
    const weekOffset = getLAOffset();
    const calUrl = `https://www.googleapis.com/calendar/v3/calendars/${TONY_EMAIL}/events?timeMin=${monday}T00:00:00${weekOffset}&timeMax=${friday}T23:59:59${weekOffset}&singleEvents=true&orderBy=startTime&maxResults=50`;
    const calRes = await fetchT(calUrl, {
      headers: { Authorization: `Bearer ${calToken}` },
    });
    const calData = calRes.ok ? await calRes.json() : { items: [] };
    const nextWeekCal = (calData.items || [])
      .map((e: any) => {
        const day = e.start?.dateTime
          ? new Date(e.start.dateTime).toLocaleDateString("en-US", {
              weekday: "short",
              timeZone: "America/Los_Angeles",
            })
          : "All day";
        const time = e.start?.dateTime
          ? new Date(e.start.dateTime).toLocaleTimeString("en-US", {
              hour: "numeric",
              minute: "2-digit",
              timeZone: "America/Los_Angeles",
            })
          : "";
        return `• ${day} ${time} — ${e.summary || "Busy"}`;
      })
      .join("\n") || "Calendar is clear.";

    const thisMonday = getThisWeekMondayLA();
    const { data: weekActions } = await svc
      .from("system_audit_log")
      .select("summary, edge_function")
      .gte("created_at", `${thisMonday}T00:00:00`)
      .not("channel", "eq", "cron")
      .order("created_at", { ascending: false })
      .limit(20);
    const weekActionsText = (weekActions || [])
      .map((a: any) => `• [${a.edge_function}] ${a.summary}`)
      .join("\n") || "No notable actions this week.";

    const { data: overdueT } = await svc
      .from("janus_reminders")
      .select("reminder_text,due_at")
      .is("fired_at", null)
      .lte("due_at", new Date().toISOString())
      .limit(10);
    const overdueTasks = (overdueT || [])
      .map((r: any) => `• ${r.reminder_text} (due ${r.due_at})`)
      .join("\n") || "No overdue tasks.";

    const { data: pendR } = await svc
      .from("janus_reminders")
      .select("reminder_text,due_at")
      .is("fired_at", null)
      .gt("due_at", new Date().toISOString())
      .order("due_at", { ascending: true })
      .limit(5);
    const reminders = (pendR || [])
      .map((r: any) => `• ${r.reminder_text} (${r.due_at})`)
      .join("\n") || "No pending reminders.";

    const { data: autoLogs } = await svc
      .from("family_automation_logs")
      .select("status, automation_id")
      .gte("started_at", `${thisMonday}T00:00:00`);
    const total = (autoLogs || []).length;
    const succeeded = (autoLogs || []).filter(
      (a: any) => a.status === "success",
    ).length;
    const automationPerf =
      total > 0
        ? `${succeeded}/${total} automations succeeded this week.`
        : "No automations ran this week.";

    const rawContext = [
      `Weekly Planning Email — ${dateStr}`,
      `Next week: ${nextWeekLabel}`,
      "",
      "NEXT WEEK'S CALENDAR:",
      nextWeekCal,
      "",
      "THIS WEEK'S ACTIONS:",
      weekActionsText,
      "",
      "OVERDUE TASKS:",
      overdueTasks,
      "",
      "PENDING REMINDERS:",
      reminders,
      "",
      "AUTOMATION PERFORMANCE:",
      automationPerf,
    ].join("\n");

    const summary = await callAI(
      `You are Janus, the household's AI chief of staff. Write a concise weekly planning email. Use a warm, professional tone. Format as clean HTML for email. Include: Next Week Preview, This Week Review, Action Items. Keep under 500 words.`,
      rawContext,
      3000,
    );

    const subject = `Weekly Plan — ${nextWeekLabel}`;
    const sent = await sendGmailRaw(
      saKey,
      TONY_EMAIL,
      subject,
      summary,
      rawContext,
    );

    const hasOverdue = overdueTasks.includes("•");
    await sendWhatsApp(
      `Weekly planning email sent. Next week: ${nextWeekLabel}.${hasOverdue ? " Heads up — you have overdue tasks to review." : " All tasks on track."}`,
    );

    logAudit("weekly-planning-email", {
      category: "automation",
      event_type: "weekly_planning_email",
      severity: "info",
      actor_id: "system",
      actor_name: "Janus",
      channel: "cron",
      summary: `Weekly planning email sent for ${nextWeekLabel}${sent ? "" : " (email failed)"}`,
      status: sent ? "success" : "partial",
      duration_ms: Date.now() - t0,
    });

    return res.json({
      ok: true,
      email_sent: sent,
      next_week: nextWeekLabel,
      duration_ms: Date.now() - t0,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : "unknown";
    logAudit("weekly-planning-email", {
      category: "automation",
      event_type: "weekly_planning_email",
      severity: "error",
      actor_id: "system",
      channel: "cron",
      summary: `Weekly planning error: ${msg.slice(0, 100)}`,
      status: "error",
      duration_ms: Date.now() - t0,
    });
    await enqueueFailedJob("weekly-planning-email", e);
    return res.status(500).json({ ok: false, error: msg });
  }
});

type Status = "ok" | "degraded" | "error";
interface CheckResult {
  name: string;
  label: string;
  category: string;
  status: Status;
  latency_ms: number;
  message: string | null;
}

async function runCheck(
  name: string,
  label: string,
  category: string,
  fn: () => Promise<string | null>,
): Promise<CheckResult> {
  const start = Date.now();
  try {
    const error = await fn();
    return {
      name,
      label,
      category,
      status: error ? "error" : "ok",
      latency_ms: Date.now() - start,
      message: error,
    };
  } catch (e) {
    return {
      name,
      label,
      category,
      status: "error",
      latency_ms: Date.now() - start,
      message: e instanceof Error ? e.message : "Unknown error",
    };
  }
}

function statusIcon(s: Status): string {
  if (s === "ok") return "✅";
  if (s === "degraded") return "⚠️";
  return "❌";
}

function statusColor(s: Status): string {
  if (s === "ok") return "#4ade80";
  if (s === "degraded") return "#fb923c";
  return "#f87171";
}

function statusBg(s: Status): string {
  if (s === "ok") return "#0a2015";
  if (s === "degraded") return "#2a1a06";
  return "#2a0a0a";
}

function buildStatusHtml(
  results: CheckResult[],
  totalMs: number,
  runTime: string,
): string {
  const overall: Status = results.some((r) => r.status === "error")
    ? "error"
    : results.some((r) => r.status === "degraded")
      ? "degraded"
      : "ok";
  const okCount = results.filter((r) => r.status === "ok").length;
  const warnCount = results.filter((r) => r.status === "degraded").length;
  const errCount = results.filter((r) => r.status === "error").length;
  const overallLabel =
    overall === "ok"
      ? "ALL SYSTEMS OPERATIONAL"
      : overall === "degraded"
        ? "DEGRADED — ACTION ADVISED"
        : "CRITICAL — SYSTEMS DOWN";
  const overallBg =
    overall === "ok"
      ? "linear-gradient(135deg,#0d3320,#1a5c35)"
      : overall === "degraded"
        ? "linear-gradient(135deg,#3a2200,#7a4a00)"
        : "linear-gradient(135deg,#3a0000,#7a1010)";

  const categories = Array.from(new Set(results.map((r) => r.category)));
  let categoryHtml = "";
  for (const cat of categories) {
    const catResults = results.filter((r) => r.category === cat);
    const rows = catResults
      .map(
        (r) => `
      <tr style="border-bottom:1px solid #1f2028;">
        <td style="padding:10px 12px;font-size:13px;color:#ece5db;">${r.label}</td>
        <td style="padding:10px 12px;text-align:center;">
          <span style="display:inline-block;padding:3px 10px;border-radius:12px;font-size:11px;font-weight:700;background:${statusBg(r.status)};color:${statusColor(r.status)};border:1px solid ${statusColor(r.status)}40;">
            ${statusIcon(r.status)} ${r.status.toUpperCase()}
          </span>
        </td>
        <td style="padding:10px 12px;text-align:right;font-size:12px;font-family:monospace;color:#8a8578;">${r.latency_ms}ms</td>
        <td style="padding:10px 12px;font-size:11px;color:${r.message ? "#f87171" : "#8a8578"};max-width:280px;word-break:break-word;">${r.message || "—"}</td>
      </tr>`,
      )
      .join("");

    categoryHtml += `
      <div style="margin-bottom:20px;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.12em;color:#f1a329;text-transform:uppercase;border-left:3px solid #f1a329;padding-left:10px;margin-bottom:8px;">${cat}</div>
        <table style="width:100%;border-collapse:collapse;background:#1c1d24;border-radius:8px;overflow:hidden;border:1px solid #2a2b33;">
          <thead><tr style="background:#14151c;">
            <th style="padding:8px 12px;text-align:left;font-size:10px;color:#8a8578;font-weight:600;">SERVICE</th>
            <th style="padding:8px 12px;text-align:center;font-size:10px;color:#8a8578;font-weight:600;">STATUS</th>
            <th style="padding:8px 12px;text-align:right;font-size:10px;color:#8a8578;font-weight:600;">LATENCY</th>
            <th style="padding:8px 12px;font-size:10px;color:#8a8578;font-weight:600;">DETAIL</th>
          </tr></thead>
          <tbody>${rows}</tbody>
        </table>
      </div>`;
  }

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#141519;font-family:'Inter',sans-serif;color:#ece5db;">
<div style="max-width:680px;margin:0 auto;padding:20px 12px;">
  <div style="background:${overallBg};border-radius:12px;padding:24px;margin-bottom:20px;text-align:center;">
    <div style="font-size:28px;font-weight:700;color:#ece5db;">${statusIcon(overall)} JANUS EXECUTIVE REPORT</div>
    <div style="font-size:13px;color:rgba(236,229,219,0.7);margin-top:4px;">${runTime} · Club 34 Systems</div>
    <div style="margin-top:14px;padding:10px 20px;background:rgba(0,0,0,0.3);border-radius:8px;display:inline-block;">
      <span style="font-size:16px;font-weight:700;color:${statusColor(overall)};">${overallLabel}</span>
    </div>
  </div>
  <div style="display:flex;gap:12px;margin-bottom:20px;">
    <div style="flex:1;background:#1c1d24;border:1px solid #2a2b33;border-radius:8px;padding:14px;text-align:center;">
      <div style="font-size:28px;font-weight:700;color:#4ade80;">${okCount}</div><div style="font-size:10px;color:#8a8578;">Operational</div>
    </div>
    <div style="flex:1;background:#1c1d24;border:1px solid #2a2b33;border-radius:8px;padding:14px;text-align:center;">
      <div style="font-size:28px;font-weight:700;color:#fb923c;">${warnCount}</div><div style="font-size:10px;color:#8a8578;">Degraded</div>
    </div>
    <div style="flex:1;background:#1c1d24;border:1px solid #2a2b33;border-radius:8px;padding:14px;text-align:center;">
      <div style="font-size:28px;font-weight:700;color:#f87171;">${errCount}</div><div style="font-size:10px;color:#8a8578;">Failed</div>
    </div>
    <div style="flex:1;background:#1c1d24;border:1px solid #2a2b33;border-radius:8px;padding:14px;text-align:center;">
      <div style="font-size:28px;font-weight:700;color:#ece5db;">${(totalMs / 1000).toFixed(1)}s</div><div style="font-size:10px;color:#8a8578;">Scan Time</div>
    </div>
  </div>
  ${categoryHtml}
  <div style="text-align:center;padding:16px;font-size:10px;color:#8a8578;">Janus Executive Status Report · Automated daily at 8:00 AM PT</div>
</div></body></html>`;
}

router.post("/executive-status", requireAuth, async (_req: Request, res: Response) => {
  const startTime = Date.now();
  const { query: dbQuery } = await import('../lib/db.js');
  const execStatusDate = new Date().toLocaleDateString("en-CA", { timeZone: "America/Los_Angeles" });
  try {
    await dbQuery(
      `INSERT INTO report_email_dedup (report_type, period_key)
       VALUES ($1, $2)`,
      ['executive-status', execStatusDate],
    );
  } catch (dedupErr: unknown) {
    if (typeof dedupErr === 'object' && dedupErr !== null && (dedupErr as { code?: string }).code === '23505') {
      console.log(`[executive-status] Skipping duplicate — already sent for ${execStatusDate}`);
      return res.json({ ok: true, skipped: true, reason: 'already_sent_today', period: execStatusDate });
    }
    throw dedupErr;
  }

  const saKey = getSaKey();
  const runTime = new Date().toLocaleString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZone: "America/Los_Angeles",
  });

  const results = await Promise.all([
    runCheck("ai_gateway", "OpenRouter AI Gateway", "AI & Intelligence", async () => {
      const key = process.env.OPENROUTER_API_KEY;
      if (!key) return "Missing OPENROUTER_API_KEY";
      const r = await fetchT("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
        body: JSON.stringify({ model: "google/gemini-2.5-flash", max_tokens: 5, messages: [{ role: "user", content: "Reply with OK" }] }),
      }, 15_000);
      if (!r.ok) return `Lovable AI HTTP ${r.status}`;
      return null;
    }),
    runCheck("home_assistant", "Home Assistant", "Smart Home Infrastructure", async () => {
      const url = process.env.HA_URL;
      const token = process.env.HA_TOKEN;
      if (!url || !token) return "Missing HA_URL or HA_TOKEN";
      const r = await fetchT(`${url}/api/`, { headers: { Authorization: `Bearer ${token}` } }, 10_000);
      if (!r.ok) return `Home Assistant HTTP ${r.status}`;
      return null;
    }),
    runCheck("notion", "Notion", "Data Layer", async () => {
      const key = process.env.NOTION_API_KEY;
      if (!key) return "Missing NOTION_API_KEY";
      const r = await fetchT("https://api.notion.com/v1/users/me", {
        headers: { Authorization: `Bearer ${key}`, "Notion-Version": "2022-06-28" },
      }, 10_000);
      if (!r.ok) return `Notion HTTP ${r.status}`;
      return null;
    }),
    runCheck("memory_db", "Janus Memory DB", "Data Layer", async () => {
      const svc = getServiceClient();
      const { error } = await svc.from("janus_memory").select("id").limit(1);
      if (error) return `Memory DB error: ${error.message}`;
      return null;
    }),
    runCheck("wati", "Janus WhatsApp (WATI)", "Janus Channels", async () => {
      const endpoint = process.env.WATI_API_ENDPOINT;
      const token = process.env.WATI_ACCESS_TOKEN;
      if (!endpoint || !token) return "Missing WATI_API_ENDPOINT or WATI_ACCESS_TOKEN";
      const serverRoot = endpoint.replace(/\/$/, "").replace(/\/api\/ext\/v3\/?$/, "").replace(/\/api\/ext\/?$/, "");
      const r = await fetchT(`${serverRoot}/api/ext/v3/getContacts?pageSize=1`, {
        headers: { Authorization: `Bearer ${token}` },
      }, 10_000);
      if (!r.ok) return `WATI HTTP ${r.status}`;
      return null;
    }),
    runCheck("elevenlabs", "ElevenLabs Voice", "AI & Intelligence", async () => {
      const key = process.env.ELEVENLABS_API_KEY;
      if (!key) return "Missing ELEVENLABS_API_KEY";
      const r = await fetchT("https://api.elevenlabs.io/v1/user", {
        headers: { "xi-api-key": key },
      }, 10_000);
      if (!r.ok) return `ElevenLabs HTTP ${r.status}`;
      return null;
    }),
    runCheck("google_calendar", "Google Calendar", "Google Workspace", async () => {
      try {
        const token = await getServiceToken(saKey, "https://www.googleapis.com/auth/calendar.readonly", TONY_EMAIL);
        const r = await fetchT(`https://www.googleapis.com/calendar/v3/calendars/${TONY_EMAIL}/events?maxResults=1`, {
          headers: { Authorization: `Bearer ${token}` },
        }, 10_000);
        if (!r.ok) return `Calendar HTTP ${r.status}`;
        return null;
      } catch (e) { return e instanceof Error ? e.message : "Calendar error"; }
    }),
    runCheck("google_drive", "Google Drive", "Google Workspace", async () => {
      try {
        const token = await getServiceToken(saKey, "https://www.googleapis.com/auth/drive.readonly", TONY_EMAIL);
        const r = await fetchT("https://www.googleapis.com/drive/v3/files?pageSize=1", {
          headers: { Authorization: `Bearer ${token}` },
        }, 10_000);
        if (!r.ok) return `Drive HTTP ${r.status}`;
        return null;
      } catch (e) { return e instanceof Error ? e.message : "Drive error"; }
    }),
    runCheck("pollen", "Pollen API", "Google Maps Platform", async () => {
      const key = process.env.GOOGLE_MAPS_API_KEY;
      if (!key) return "Missing GOOGLE_MAPS_API_KEY";
      const r = await fetchT(`https://pollen.googleapis.com/v1/forecast:lookup?key=${key}&location.latitude=${HOME_LAT}&location.longitude=${HOME_LNG}&days=1`, undefined, 10_000);
      if (!r.ok) return `Pollen HTTP ${r.status}`;
      return null;
    }),
    runCheck("firecrawl", "Firecrawl Web Search", "AI & Intelligence", async () => {
      const key = process.env.FIRECRAWL_API_KEY;
      if (!key) return "Missing FIRECRAWL_API_KEY";
      const r = await fetchT("https://api.firecrawl.dev/v1/search", {
        method: "POST",
        headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
        body: JSON.stringify({ query: "test", limit: 1 }),
      }, 15_000);
      if (!r.ok) return `Firecrawl HTTP ${r.status}`;
      return null;
    }),
  ]);

  const totalMs = Date.now() - startTime;
  const overall: Status = results.some((r) => r.status === "error")
    ? "error"
    : results.some((r) => r.status === "degraded")
      ? "degraded"
      : "ok";

  const errCount = results.filter((r) => r.status === "error").length;
  const warnCount = results.filter((r) => r.status === "degraded").length;
  const emoji =
    overall === "ok" ? "✅" : overall === "degraded" ? "⚠️" : "🚨";
  const subject = `${emoji} Janus Status — ${errCount > 0 ? `${errCount} FAILED` : warnCount > 0 ? `${warnCount} DEGRADED` : "All Systems Go"} · ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "America/Los_Angeles" })}`;

  const html = buildStatusHtml(results, totalMs, runTime);
  const textLines = results.map(
    (r) =>
      `${statusIcon(r.status)} ${r.label}: ${r.status.toUpperCase()} (${r.latency_ms}ms)${r.message ? ` — ${r.message}` : ""}`,
  );
  const text = `JANUS EXECUTIVE REPORT — ${runTime}\n\n${textLines.join("\n")}`;

  const sent = await sendGmailRaw(saKey, TONY_EMAIL, subject, html, text);

  await logEmail(
    "executive_status",
    subject,
    [TONY_EMAIL],
    html,
    sent ? "sent" : "error",
    sent ? undefined : "sendStatusEmail returned false",
    text,
  );

  const svc = getServiceClient();
  await svc.from("janus_health_logs").insert({
    results,
    overall_status: overall,
    total_ms: totalMs,
  });

  return res.json({
    ok: true,
    overall,
    total_ms: totalMs,
    checks: results.length,
    email_sent: sent,
  });
});

interface NewsItem {
  title: string;
  source: string;
  url: string;
}
interface WeatherSlot {
  label: string;
  icon: string;
  temp: number;
}
interface CalEvent {
  time: string;
  event: string;
  allDay?: boolean;
}

function weatherCodeToDescription(code: number): string {
  const map: Record<number, string> = {
    0: "Clear sky ☀️",
    1: "Mainly clear 🌤️",
    2: "Partly cloudy ⛅",
    3: "Overcast ☁️",
    45: "Foggy 🌫️",
    48: "Icy fog 🌫️",
    51: "Light drizzle 🌦️",
    53: "Drizzle 🌦️",
    55: "Heavy drizzle 🌧️",
    61: "Light rain 🌧️",
    63: "Rain 🌧️",
    65: "Heavy rain 🌧️",
    71: "Light snow 🌨️",
    73: "Snow 🌨️",
    75: "Heavy snow 🌨️",
    80: "Light showers 🌦️",
    81: "Showers 🌧️",
    82: "Heavy showers ⛈️",
    95: "Thunderstorm ⛈️",
  };
  return map[code] || `Code ${code}`;
}

interface EmailData {
  subject: string;
  weather: {
    condition: string;
    icon: string;
    tempNow: number | null;
    feelsLike: number | null;
    slots: WeatherSlot[];
    wardrobeTip: string;
    rainAlert: string | null;
    asOf: string | null;
    source: "Google Weather" | "Open-Meteo" | null;
  };
  markets: MarketSnapshot;
  news: { us: NewsItem[]; world: NewsItem[] };
  childSchedule: CalEvent[];
  dadSchedule: CalEvent[];
  momSchedule: CalEvent[];
}

function weatherCodeToEmoji(code: number): string {
  const desc = weatherCodeToDescription(code);
  const match = desc.match(/[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/u);
  return match ? match[0] : "🌡️";
}

/** Google Weather API condition type → human-readable description (parallel to weatherCodeToDescription). */
function googleConditionToDescription(type: string): string {
  return googleCondToDescription(type);
}

/** Google Weather API condition type → single emoji (parallel to weatherCodeToEmoji). */
function googleConditionToEmoji(type: string): string {
  return googleCondToEmoji(type);
}

function formatCalendarForAI(events: any[]): CalEvent[] {
  if (!events.length) return [];
  return events.map(e => {
    if (e.allDay) return { time: "All day", event: e.summary, allDay: true };
    const st = new Date(e.start).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", timeZone: "America/Los_Angeles" });
    return { time: st, event: e.summary };
  });
}

async function generateEmailData(
  childName: string,
  weatherSummary: string,
  weatherRaw: WeatherSourceData | null,
  news: { us: NewsItem[]; world: NewsItem[] },
  financial: MarketSnapshot,
  childEvents: any[],
  dadEvents: any[],
  momEvents: any[],
): Promise<EmailData> {
  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long", month: "long", day: "numeric", year: "numeric", timeZone: "America/Los_Angeles",
  });

  const childCal = formatCalendarForAI(childEvents);
  const dadCal = formatCalendarForAI(dadEvents);
  const momCal = formatCalendarForAI(momEvents);
  const rawWeather = weatherRaw
    ? extractWeatherData(weatherRaw)
    : { current: null, slots: [] };
  const slotLabels = new Map([
    [8, "Morning"],
    [12, "Midday"],
    [15, "Afternoon"],
    [19, "Evening"],
  ]);
  const exactWeather = {
    condition: rawWeather.current
      ? weatherCodeToDescription(rawWeather.current.code).replace(
          /\s*[\u{1F300}-\u{1F9FF}\u{2600}-\u{27BF}]+\s*$/u,
          "",
        )
      : "Unavailable",
    icon: rawWeather.current ? weatherCodeToEmoji(rawWeather.current.code) : "🌡️",
    tempNow: rawWeather.current?.temp ?? null,
    feelsLike: rawWeather.current?.feels ?? null,
    slots: rawWeather.slots.map((slot) => ({
      label: slotLabels.get(slot.hour) ?? `${slot.hour}:00`,
      icon: weatherCodeToEmoji(slot.code),
      temp: slot.temp,
    })),
    wardrobeTip: (() => {
      const temperatures = [
        rawWeather.current?.temp,
        ...rawWeather.slots.map((slot) => slot.temp),
      ].filter((temp): temp is number => typeof temp === "number");
      const rainChance = Math.max(0, ...rawWeather.slots.map((slot) => slot.precip));
      if (temperatures.length === 0) return "Weather data unavailable";
      const low = Math.min(...temperatures);
      const high = Math.max(...temperatures);
      if (rainChance >= 40) return "Bring an umbrella or rain layer";
      if (high >= 85) return "It will be hot this afternoon — wear light clothing and bring water";
      if (low <= 60 && high >= 75) return "Start with a light layer you can remove as it warms up";
      if (low <= 60) return "A light jacket or sweater will help this morning";
      return "Comfortable, light layers should work well today";
    })(),
    rainAlert: (() => {
      const wettest = [...rawWeather.slots].sort(
        (left, right) => right.precip - left.precip,
      )[0];
      if (!wettest || wettest.precip < 40) return null;
      const label = slotLabels.get(wettest.hour) ?? `${wettest.hour}:00`;
      return `${Math.round(wettest.precip)}% chance of rain around ${label.toLowerCase()}`;
    })(),
    asOf: weatherRaw?.current?.observedAt
      ? new Date(weatherRaw.current.observedAt).toLocaleTimeString("en-US", {
          timeZone: "America/Los_Angeles",
          hour: "numeric",
          minute: "2-digit",
          timeZoneName: "short",
        })
      : null,
    source: weatherRaw?.source ?? null,
  };

  const prompt = `You are Janus. Today is ${today}. Generate a morning briefing JSON for ${childName} (teenage girl).

Return ONLY valid JSON matching this exact schema (no markdown, no extra fields):
{
  "subject": "☀️ Good Morning, ${childName}! · ${today}",
  "weather": {
    "condition": "brief description e.g. Sunny",
    "icon": "single weather emoji",
    "tempNow": ${rawWeather.current?.temp ?? "null"},
    "feelsLike": ${rawWeather.current?.feels ?? "null"},
    "slots": [
      {"label":"Morning","icon":"emoji","temp":number},
      {"label":"Midday","icon":"emoji","temp":number},
      {"label":"Afternoon","icon":"emoji","temp":number},
      {"label":"Evening","icon":"emoji","temp":number}
    ],
    "wardrobeTip": "1 short practical tip for what to wear/bring",
    "rainAlert": null or "Rain likely at 2pm — bring umbrella"
  },
  "markets": {
    "indices": [{"name":"string","value":"string","change":"string","up":boolean}],
    "commodities": [{"name":"string","value":"string","change":"string","up":boolean}],
    "currencies": [{"name":"string","value":"string","change":"string","up":boolean}]
  },
  "childSchedule": [{"time":"9:00 AM","event":"string","allDay":false}],
  "dadSchedule": [{"time":"string","event":"string"}],
  "momSchedule": [{"time":"string","event":"string"}]
}

Data inputs:
WEATHER (full day 6am–11pm): ${weatherSummary.split('\n').slice(0, 20).join('\n')}
FINANCIAL (use this data, don't make up different numbers): ${JSON.stringify(financial)}
${childName.toUpperCase()}'S CALENDAR: ${JSON.stringify(childCal)}
DAD'S CALENDAR: ${JSON.stringify(dadCal)}
MOM'S CALENDAR: ${JSON.stringify(momCal)}

CRITICAL: Use the EXACT financial values from the input. Do not fabricate data. For weather slots, use the actual hourly data above to pick realistic temps and emojis for Morning (8am), Midday (12pm), Afternoon (3pm), Evening (7pm).`;

  const sanitizeString = (s: any, fallback: string, maxLen = 200): string => {
    if (typeof s !== "string") return fallback;
    return s.replace(/<[^>]*>/g, "").trim().slice(0, maxLen) || fallback;
  };

  const sanitizeEmailData = (parsed: any): EmailData => {
    return {
      subject: sanitizeString(parsed?.subject, `☀️ Good Morning, ${childName}! · ${today}`, 150),
      weather: exactWeather,
      markets: financial,
      news,
      childSchedule: Array.isArray(parsed?.childSchedule) ? parsed.childSchedule : childCal,
      dadSchedule: Array.isArray(parsed?.dadSchedule) ? parsed.dadSchedule : dadCal,
      momSchedule: Array.isArray(parsed?.momSchedule) ? parsed.momSchedule : momCal,
    };
  };

  try {
    const parsed = await callAIJSON(prompt, 4000);
    return sanitizeEmailData(parsed);
  } catch {
    return {
      subject: `☀️ Good Morning, ${childName}! · ${today}`,
      weather: exactWeather,
      markets: financial,
      news,
      childSchedule: childCal,
      dadSchedule: dadCal,
      momSchedule: momCal,
    };
  }
}

function buildEmailHtml(childName: string, data: EmailData, today: string): string {
  const { weather, markets, news, childSchedule, dadSchedule, momSchedule } = data;

  const marketRow = (item: MarketItem) => {
    const color = item.up ? "#16a34a" : "#dc2626";
    const arrow = item.up ? "▲" : "▼";
    return `
      <tr>
        <td style="padding:6px 10px 6px 0;font-size:13px;color:#111827;border-bottom:1px solid #f3f4f6;">${escapeHtml(item.name)}</td>
        <td style="padding:6px 10px;font-size:13px;font-family:'Courier New',monospace;color:#111827;border-bottom:1px solid #f3f4f6;text-align:right;">${escapeHtml(item.value)}</td>
        <td style="padding:6px 0 6px 10px;font-size:13px;font-family:'Courier New',monospace;color:${color};border-bottom:1px solid #f3f4f6;text-align:right;white-space:nowrap;">${arrow} ${escapeHtml(item.change)}</td>
      </tr>`;
  };

  const marketGroupHeader = (label: string) => `
    <tr>
      <td colspan="3" style="padding:8px 10px 4px 0;font-size:10px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#9ca3af;border-bottom:2px solid #e5e7eb;">${escapeHtml(label)}</td>
    </tr>`;

  const scheduleRows = (events: CalEvent[]) => {
    if (!events.length) return `<tr><td colspan="2" style="padding:6px 0;font-size:12px;color:#9ca3af;font-style:italic;">No events today</td></tr>`;
    const allDayEvents = events.filter(e => e.allDay);
    const timedEvents = events.filter(e => !e.allDay);
    let rows = "";
    if (allDayEvents.length) {
      rows += `<tr><td colspan="2" style="padding:4px 0 8px;">${allDayEvents.map(e => `<span style="display:inline-block;background:#fef3c7;color:#92400e;font-size:11px;font-weight:600;padding:2px 8px;border-radius:12px;margin-right:4px;">${escapeHtml(e.event)}</span>`).join("")}</td></tr>`;
    }
    rows += timedEvents.map(e => `
      <tr>
        <td style="padding:5px 12px 5px 0;font-size:12px;color:#6b7280;white-space:nowrap;vertical-align:top;min-width:70px;">${escapeHtml(e.time)}</td>
        <td style="padding:5px 0;font-size:13px;color:#111827;">${escapeHtml(e.event)}</td>
      </tr>`).join("");
    return rows;
  };

  const newsSection = (flag: string, label: string, items: NewsItem[]) => {
    if (!items.length) return "";
    const headlines = items.slice(0, 5).map(item => {
      const url = item.url || "#";
      return `<div style="padding:5px 0;border-bottom:1px solid #f3f4f6;line-height:1.4;">
        <a href="${escapeHtml(url)}" style="color:#92400e;text-decoration:underline;font-weight:500;font-size:13px;">${escapeHtml(item.title)}</a>
        ${item.source ? `<span style="color:#9ca3af;font-size:11px;margin-left:6px;">— ${escapeHtml(item.source)}</span>` : ""}
      </div>`;
    }).join("");
    return `
      <div style="margin-bottom:20px;">
        <div style="font-size:11px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#6b7280;border-left:3px solid #f59e0b;padding-left:8px;margin-bottom:10px;">${flag} ${escapeHtml(label)}</div>
        ${headlines}
      </div>`;
  };

  const slotLabels: Record<string, string> = { Morning: "8am", Midday: "12pm", Afternoon: "3pm", Evening: "7pm" };
  const weatherStrip = weather.slots.slice(0, 4).map(slot => `
    <td style="text-align:center;padding:0 4px;width:80px;">
      <div style="background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;padding:10px 8px;">
        <div style="font-size:22px;line-height:1;">${slot.icon}</div>
        <div style="font-size:10px;color:#9ca3af;margin-top:4px;font-weight:500;">${slotLabels[slot.label] || escapeHtml(slot.label)}</div>
        <div style="font-size:14px;font-weight:700;color:#111827;margin-top:2px;">${slot.temp}°</div>
      </div>
    </td>`).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>Good Morning, ${escapeHtml(childName)}!</title>
</head>
<body style="margin:0;padding:0;background-color:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;-webkit-text-size-adjust:100%;mso-line-height-rule:exactly;">

<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f3f4f6;">
<tr><td align="center" style="padding:20px 12px;">

  <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <tr>
      <td style="background-color:#f59e0b;padding:28px 32px 24px;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td style="vertical-align:middle;">
              <div style="font-family:Georgia,'Times New Roman',serif;font-size:28px;font-weight:700;color:#ffffff;line-height:1.2;letter-spacing:-0.5px;">
                Good Morning, ${escapeHtml(childName)}! 🌸
              </div>
              <div style="font-size:13px;color:rgba(255,255,255,0.85);margin-top:6px;font-weight:500;letter-spacing:0.02em;">
                ${escapeHtml(today)} &nbsp;·&nbsp; Your Daily Briefing from Janus
              </div>
            </td>
            <td style="vertical-align:middle;text-align:right;padding-left:16px;width:60px;">
              <img src="https://example.com/icon.svg" alt="Janus" width="48" height="48" style="border-radius:50%;border:2px solid rgba(255,255,255,0.4);display:block;" />
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <tr>
      <td style="padding:24px 32px 20px;border-bottom:1px solid #f3f4f6;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#6b7280;border-left:3px solid #f59e0b;padding-left:8px;margin-bottom:14px;">🌡️ Weather · Beverly Hills</div>
        ${weather.source ? `<div style="font-size:10px;color:#9ca3af;margin:-8px 0 10px 11px;">Live ${escapeHtml(weather.source)} data${weather.asOf ? ` · as of ${escapeHtml(weather.asOf)}` : ""}</div>` : ""}
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td style="vertical-align:middle;width:140px;">
              <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:10px;padding:14px 16px;text-align:center;">
                <div style="font-size:36px;line-height:1;">${weather.icon}</div>
                <div style="font-size:26px;font-weight:800;color:#111827;margin-top:4px;">${weather.tempNow === null ? "Unavailable" : `${weather.tempNow}°F`}</div>
                <div style="font-size:11px;color:#92400e;font-weight:600;margin-top:2px;">${escapeHtml(weather.condition)}</div>
                ${weather.feelsLike === null ? "" : `<div style="font-size:11px;color:#9ca3af;margin-top:2px;">Feels ${weather.feelsLike}°</div>`}
              </div>
            </td>
            <td style="padding-left:10px;vertical-align:middle;">
              <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tr>${weatherStrip}</tr>
              </table>
            </td>
          </tr>
        </table>
        ${weather.rainAlert ? `<div style="margin-top:12px;background:#fef2f2;border:1px solid #fca5a5;border-radius:6px;padding:8px 12px;font-size:12px;color:#991b1b;">☂️ <strong>${escapeHtml(weather.rainAlert)}</strong></div>` : ""}
        <div style="margin-top:10px;font-size:12px;color:#b45309;font-style:italic;">👗 ${escapeHtml(weather.wardrobeTip)}</div>
      </td>
    </tr>

    <tr>
      <td style="padding:20px 32px;border-bottom:1px solid #f3f4f6;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#6b7280;border-left:3px solid #f59e0b;padding-left:8px;margin-bottom:12px;">📈 Markets</div>
        ${markets.asOf ? `<div style="font-size:10px;color:#9ca3af;margin:-6px 0 10px 11px;">Live CNBC data · as of ${escapeHtml(markets.asOf)}</div>` : ""}
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          ${markets.indices?.length ? `${marketGroupHeader("Indices")}${markets.indices.map(marketRow).join("")}` : ""}
          ${markets.commodities?.length ? `${marketGroupHeader("Commodities")}${markets.commodities.map(marketRow).join("")}` : ""}
          ${markets.currencies?.length ? `${marketGroupHeader("Currencies")}${markets.currencies.map(marketRow).join("")}` : ""}
          ${!markets.indices.length && !markets.commodities.length && !markets.currencies.length ? `<tr><td style="padding:8px 0;font-size:12px;color:#9ca3af;">Market data unavailable</td></tr>` : ""}
        </table>
      </td>
    </tr>

    <tr>
      <td style="padding:20px 32px;border-bottom:1px solid #f3f4f6;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#6b7280;border-left:3px solid #f59e0b;padding-left:8px;margin-bottom:12px;">📅 ${escapeHtml(childName)}'s Schedule</div>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          ${scheduleRows(childSchedule)}
        </table>
      </td>
    </tr>

    <tr>
      <td style="padding:20px 32px;border-bottom:1px solid #f3f4f6;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#6b7280;border-left:3px solid #f59e0b;padding-left:8px;margin-bottom:14px;">📰 Headlines</div>
        ${newsSection("🇺🇸", "US News", news.us)}
        ${newsSection("🌎", "World News", news.world)}
      </td>
    </tr>

    <tr>
      <td style="padding:20px 32px;border-bottom:1px solid #f3f4f6;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#6b7280;border-left:3px solid #f59e0b;padding-left:8px;margin-bottom:12px;">👨‍👩‍👧‍👧 Family Calendars</div>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr valign="top">
            <td style="width:50%;padding-right:8px;">
              <div style="border-left:3px solid #b45309;padding-left:10px;">
                <div style="font-size:11px;font-weight:700;color:#b45309;margin-bottom:8px;letter-spacing:0.05em;">👨 Dad</div>
                <table width="100%" cellpadding="0" cellspacing="0" border="0">
                  ${scheduleRows(dadSchedule)}
                </table>
              </div>
            </td>
            <td style="width:50%;padding-left:8px;">
              <div style="border-left:3px solid #f59e0b;padding-left:10px;">
                <div style="font-size:11px;font-weight:700;color:#b45309;margin-bottom:8px;letter-spacing:0.05em;">👩 Mom</div>
                <table width="100%" cellpadding="0" cellspacing="0" border="0">
                  ${scheduleRows(momSchedule)}
                </table>
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <tr>
      <td style="background-color:#f9fafb;padding:18px 32px;border-top:1px solid #e5e7eb;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td>
              <div style="font-size:13px;color:#f59e0b;font-weight:600;">Janus ✦</div>
              <div style="font-size:11px;color:#9ca3af;margin-top:2px;">Household OS · Your personal AI assistant</div>
            </td>
          </tr>
        </table>
      </td>
    </tr>

  </table>

</td></tr>
</table>

</body>
</html>`;
}

router.post("/morning-weather", requireAuth, async (_req: Request, res: Response) => {
  try {
    const { query: dbQuery } = await import('../lib/db.js');
    const mwDate = new Date().toLocaleDateString("en-CA", { timeZone: "America/Los_Angeles" });

    // Vacation mode: when the "Morning Brief Email" automation is toggled off
    // (is_active=false), pause the daily brief. Mirrors the school broadcast /
    // Morning Sauna vacation-mode pattern.
    //
    // Fail-open by design: we only skip when is_active is explicitly false. A
    // missing row, null value, or lookup error logs a warning and proceeds with
    // the brief. Checked BEFORE the dedup insert so the email can resume the same
    // day vacation mode is turned back off.
    try {
      const { rows: autoRows } = await dbQuery(
        `SELECT is_active FROM family_automations WHERE name = $1 LIMIT 1`,
        ['Morning Brief Email'],
      );
      if (autoRows[0]?.is_active === false) {
        logAudit("morning-weather-email", {
          category: "automation",
          event_type: "morning_weather_skip",
          severity: "info",
          actor_id: "system",
          actor_name: "Cron",
          channel: "cron",
          summary: `Morning Brief Email skipped: vacation mode (${mwDate})`,
          status: "skipped",
        });
        return res.json({ ok: true, skipped: true, reason: "vacation_mode", period: mwDate });
      }
    } catch (vacErr: unknown) {
      logAudit("morning-weather-email", {
        category: "automation",
        event_type: "morning_weather_vacation_lookup_failed",
        severity: "warning",
        actor_id: "system",
        actor_name: "Cron",
        channel: "cron",
        summary: `Vacation-mode lookup failed; proceeding with brief (${mwDate})`,
        status: "warning",
        detail: { error: vacErr instanceof Error ? vacErr.message : String(vacErr) },
      });
    }

    try {
      await dbQuery(
        `INSERT INTO report_email_dedup (report_type, period_key)
         VALUES ($1, $2)`,
        ['morning-weather', mwDate],
      );
    } catch (dedupErr: unknown) {
      if (typeof dedupErr === 'object' && dedupErr !== null && (dedupErr as { code?: string }).code === '23505') {
        console.log(`[morning-weather] Skipping duplicate — already sent for ${mwDate}`);
        return res.json({ ok: true, skipped: true, reason: 'already_sent_today', period: mwDate });
      }
      throw dedupErr;
    }

    const openrouterApiKey = process.env.OPENROUTER_API_KEY;
    if (!openrouterApiKey) throw new Error("OPENROUTER_API_KEY not configured");

    const saKey = getSaKey();

    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
      year: "numeric",
      timeZone: "America/Los_Angeles",
    });

    const CHILDREN = [
      {
        name: "Emme",
        recipients: ["member3@example.com", "member2@example.com"],
        calendarEmail: EMME_EMAIL,
      },
      {
        name: "Isla",
        recipients: ["member2@example.com", "member3@example.com"],
        calendarEmail: ISLA_EMAIL,
      },
    ];
    const CC_RECIPIENTS = ["admin@example.com"];

    const fetchCalendarEvents = async (email: string, _label: string) => {
      try {
        const accessToken = await getGoogleTokenFromEnv(
          "https://www.googleapis.com/auth/calendar.readonly",
          email,
        );
        const now = new Date();
        const laDate = new Date(
          now.toLocaleString("en-US", { timeZone: "America/Los_Angeles" }),
        );
        const startOfDay = new Date(laDate);
        startOfDay.setHours(0, 0, 0, 0);
        const endOfDay = new Date(laDate);
        endOfDay.setHours(23, 59, 59, 999);
        const params = new URLSearchParams({
          singleEvents: "true",
          orderBy: "startTime",
          maxResults: "50",
          timeMin: startOfDay.toISOString(),
          timeMax: endOfDay.toISOString(),
        });
        const r = await fetchT(
          `https://www.googleapis.com/calendar/v3/calendars/primary/events?${params}`,
          { headers: { Authorization: `Bearer ${accessToken}` } },
        );
        if (!r.ok) return [];
        const data = await r.json();
        return (data.items || []).map((e: any) => ({
          summary: e.summary || "Busy",
          start: e.start?.dateTime || e.start?.date,
          end: e.end?.dateTime || e.end?.date,
          allDay: !e.start?.dateTime,
        }));
      } catch (_) {
        return [];
      }
    };

    const fetchNewsRSS = async (topic: string): Promise<NewsItem[]> => {
      try {
        const url =
          topic === "world"
            ? "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en"
            : "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en";
        const r = await fetchT(url);
        if (!r.ok) return [];
        const xml = await r.text();
        const items: NewsItem[] = [];
        const itemMatches = xml.match(/<item>([\s\S]*?)<\/item>/g) || [];
        for (const item of itemMatches.slice(0, 6)) {
          const titleMatch =
            item.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/) ||
            item.match(/<title>(.*?)<\/title>/);
          const linkMatch = item.match(/<link>(.*?)<\/link>/);
          const sourceMatch = item.match(/<source[^>]*>(.*?)<\/source>/);
          if (titleMatch) {
            let title = titleMatch[1];
            let source = sourceMatch?.[1] || "";
            if (!source) {
              const dashIdx = title.lastIndexOf(" - ");
              if (dashIdx > 0) {
                source = title.substring(dashIdx + 3);
                title = title.substring(0, dashIdx);
              }
            }
            items.push({
              title,
              source,
              url: linkMatch?.[1] || "",
            });
          }
        }
        return items;
      } catch (_) {
        return [];
      }
    };

    const [
      googleCurrentRaw,
      googleHourlyRaw,
      openMeteoWeather,
      marketSnapshot,
      usNews,
      worldNews,
      dadEvents,
      momEvents,
      emmeEvents,
      islaEvents,
    ] =
      await Promise.all([
        fetchGoogleCurrentConditions(HOME_LAT, HOME_LNG),
        fetchGoogleHourlyForecast(HOME_LAT, HOME_LNG, 24),
        fetchOpenMeteoWeather(HOME_LAT, HOME_LNG),
        fetchMarketSnapshot(),
        fetchNewsRSS("us"),
        fetchNewsRSS("world"),
        fetchCalendarEvents("admin@example.com", "Dad"),
        fetchCalendarEvents("member@example.com", "Mom"),
        fetchCalendarEvents("member3@example.com", "Emme"),
        fetchCalendarEvents("member2@example.com", "Isla"),
      ]);

    const news = { us: usNews, world: worldNews };
    const googleWeather = buildWeatherSourceData(googleHourlyRaw, googleCurrentRaw);
    const weatherData =
      googleWeather?.hourly.time.length
        ? googleWeather
        : openMeteoWeather ?? googleWeather;
    const financial: MarketSnapshot = marketSnapshot ?? {
      indices: [],
      commodities: [],
      currencies: [],
      asOf: null,
      source: "CNBC",
    };

    const weatherSummary = weatherData ? formatWeatherForAI(weatherData) : "";

    const childCalendars: Record<string, any[]> = {
      Emme: emmeEvents,
      Isla: islaEvents,
    };

    console.log(`[Morning Email] Data fetched: weather ${weatherData ? "✓" : "✗"}, ${usNews.length} US / ${worldNews.length} world news, financial ${marketSnapshot ? "✓" : "✗"}, calendars (Dad:${dadEvents.length}, Mom:${momEvents.length}, Emme:${emmeEvents.length}, Isla:${islaEvents.length})`);

    const dataPromises = CHILDREN.map(child =>
      generateEmailData(
        child.name, weatherSummary, weatherData, news, financial,
        childCalendars[child.name] || [], dadEvents, momEvents,
      ).then(data => ({ child, data }))
    );
    const emailDataResults = await Promise.all(dataPromises);
    console.log("[Morning Email] AI data generated:", emailDataResults.map(r => `${r.child.name}: "${r.data.subject}"`).join(", "));

    const gmailToken = await getServiceToken(
      saKey,
      "https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly",
      JANUS_EMAIL,
    );

    const allSendResults: any[] = [];

    const childStatusMap: Record<string, string> = {};

    for (const { child, data } of emailDataResults) {
      const todayDateLA = new Date().toLocaleDateString("en-CA", { timeZone: "America/Los_Angeles" });
      const dedupCheck = await dbQuery(
        `SELECT id FROM email_logs
         WHERE email_type = 'morning_brief'
           AND metadata->>'child' = $1
           AND status = 'sent'
           AND sent_at >= $2::date
           AND sent_at < ($2::date + interval '1 day')
         LIMIT 1`,
        [child.name, todayDateLA],
      );
      if (dedupCheck.rows.length > 0) {
        console.log(`[Morning Email] Skipping ${child.name} — already sent today (dedup guard)`);
        childStatusMap[child.name] = "skipped";
        continue;
      }

      const htmlBody = buildEmailHtml(child.name, data, today);
      const textBody = [
        `GOOD MORNING, ${child.name.toUpperCase()}!`,
        today,
        "",
        data.weather.tempNow === null
          ? "WEATHER: Unavailable"
          : `WEATHER: ${data.weather.icon} ${data.weather.condition} · ${data.weather.tempNow}°F${data.weather.feelsLike === null ? "" : ` (feels ${data.weather.feelsLike}°F)`}`,
        data.weather.source
          ? `Live ${data.weather.source} data${data.weather.asOf ? ` · as of ${data.weather.asOf}` : ""}`
          : "",
        data.weather.wardrobeTip,
        data.weather.rainAlert ? `⚠️ ${data.weather.rainAlert}` : "",
        "",
        "MARKETS",
        data.markets.asOf ? `Live CNBC data · as of ${data.markets.asOf}` : "",
        ...(data.markets.indices || []).map(m => `${m.name}: ${m.value} ${m.up ? "▲" : "▼"} ${m.change}`),
        ...(data.markets.commodities || []).map(m => `${m.name}: ${m.value} ${m.up ? "▲" : "▼"} ${m.change}`),
        ...(data.markets.currencies || []).map(m => `${m.name}: ${m.value} ${m.up ? "▲" : "▼"} ${m.change}`),
        !data.markets.indices.length && !data.markets.commodities.length && !data.markets.currencies.length
          ? "Market data unavailable"
          : "",
        "",
        `${child.name.toUpperCase()}'S SCHEDULE`,
        ...(data.childSchedule.length ? data.childSchedule.map(e => `${e.time}: ${e.event}`) : ["No events today"]),
        "",
        "US NEWS",
        ...(data.news.us.slice(0, 5).map(n => `• ${n.title} — ${n.source}`)),
        "",
        "WORLD NEWS",
        ...(data.news.world.slice(0, 5).map(n => `• ${n.title} — ${n.source}`)),
        "",
        "DAD'S SCHEDULE",
        ...(data.dadSchedule.length ? data.dadSchedule.map(e => `${e.time}: ${e.event}`) : ["No events today"]),
        "",
        "MOM'S SCHEDULE",
        ...(data.momSchedule.length ? data.momSchedule.map(e => `${e.time}: ${e.event}`) : ["No events today"]),
        "",
        "— Janus · Household OS",
      ].filter(l => l !== undefined).join("\n");

      const childSendResults: { to: string; success: boolean; error?: string }[] = [];

      for (const to of child.recipients) {
        const enc = new TextEncoder();
        const boundary = "boundary_" + crypto.randomUUID().replace(/-/g, "");
        const subjectB64 = Buffer.from(data.subject).toString("base64");
        const mime = [
          `From: Janus <${JANUS_EMAIL}>`,
          `To: ${to}`,
          `Subject: =?UTF-8?B?${subjectB64}?=`,
          "MIME-Version: 1.0",
          `Content-Type: multipart/alternative; boundary="${boundary}"`,
          "",
          `--${boundary}`,
          "Content-Type: text/plain; charset=UTF-8",
          "",
          textBody,
          "",
          `--${boundary}`,
          "Content-Type: text/html; charset=UTF-8",
          "",
          htmlBody,
          "",
          `--${boundary}--`,
        ].join("\r\n");
        const raw = base64url(enc.encode(mime));

        try {
          const sendRes = await fetch(
            "https://gmail.googleapis.com/gmail/v1/users/me/messages/send",
            {
              method: "POST",
              headers: {
                Authorization: `Bearer ${gmailToken}`,
                "Content-Type": "application/json",
              },
              body: JSON.stringify({ raw }),
            },
          );
          if (!sendRes.ok) {
            const errText = await sendRes.text().catch(() => `HTTP ${sendRes.status}`);
            console.error(`[Morning Email] Send failed for ${child.name} → ${to}: ${errText}`);
            childSendResults.push({ to, success: false, error: errText });
          } else {
            childSendResults.push({ to, success: true });
          }
        } catch (err) {
          const errMsg = err instanceof Error ? err.message : String(err);
          console.error(`[Morning Email] Send exception for ${child.name} → ${to}: ${errMsg}`);
          childSendResults.push({ to, success: false, error: errMsg });
        }
      }

      allSendResults.push(...childSendResults);

      const childAllSuccess = childSendResults.every((r) => r.success);
      const childErrors = childSendResults.filter((r) => !r.success).map((r) => r.error).filter(Boolean).join("; ");
      const childLogStatus = childAllSuccess ? "sent" : (childSendResults.some((r) => r.success) ? "partial_failure" : "error");
      childStatusMap[child.name] = childLogStatus;

      await logEmail(
        "morning_brief",
        data.subject,
        child.recipients,
        htmlBody,
        childLogStatus,
        childAllSuccess ? undefined : (childErrors || "Send failed"),
        textBody,
        { child: child.name },
      );
    }

    const ccTodayDateLA = new Date().toLocaleDateString("en-CA", { timeZone: "America/Los_Angeles" });
    for (const ccEmailResult of emailDataResults) {
      const ccChildName = ccEmailResult.child.name;
      const ccMetaKey = `cc-${ccChildName}`;
      const ccDedupCheck = await dbQuery(
        `SELECT id FROM email_logs
         WHERE email_type = 'morning_brief'
           AND metadata->>'child' = $2
           AND status = 'sent'
           AND sent_at >= $1::date
           AND sent_at < ($1::date + interval '1 day')
         LIMIT 1`,
        [ccTodayDateLA, ccMetaKey],
      );
      if (ccDedupCheck.rows.length > 0) {
        console.log(`[Morning Email] Skipping CC (tony) for ${ccChildName} — already sent today (dedup guard)`);
        childStatusMap[ccMetaKey] = "skipped";
        continue;
      }
      const ccSubjectText = ccEmailResult.data.subject;
      const ccHtmlBody = buildEmailHtml(ccEmailResult.child.name, ccEmailResult.data, today);
      const ccSendResults: { to: string; success: boolean; error?: string }[] = [];
      for (const to of CC_RECIPIENTS) {
        const enc = new TextEncoder();
        const boundary = "boundary_" + crypto.randomUUID().replace(/-/g, "");
        const subjectB64 = Buffer.from(ccSubjectText).toString("base64");
        const mime = [
          `From: Janus <${JANUS_EMAIL}>`,
          `To: ${to}`,
          `Subject: =?UTF-8?B?${subjectB64}?=`,
          "MIME-Version: 1.0",
          `Content-Type: multipart/alternative; boundary="${boundary}"`,
          "",
          `--${boundary}`,
          "Content-Type: text/html; charset=UTF-8",
          "",
          ccHtmlBody,
          "",
          `--${boundary}--`,
        ].join("\r\n");
        const raw = base64url(enc.encode(mime));

        try {
          const sendRes = await fetch(
            "https://gmail.googleapis.com/gmail/v1/users/me/messages/send",
            {
              method: "POST",
              headers: {
                Authorization: `Bearer ${gmailToken}`,
                "Content-Type": "application/json",
              },
              body: JSON.stringify({ raw }),
            },
          );
          if (!sendRes.ok) {
            const errText = await sendRes.text().catch(() => `HTTP ${sendRes.status}`);
            console.error(`[Morning Email] CC send failed → ${to} (${ccChildName}): ${errText}`);
            ccSendResults.push({ to, success: false, error: errText });
          } else {
            ccSendResults.push({ to, success: true });
          }
        } catch (err) {
          const errMsg = err instanceof Error ? err.message : String(err);
          console.error(`[Morning Email] CC send exception → ${to} (${ccChildName}): ${errMsg}`);
          ccSendResults.push({ to, success: false, error: errMsg });
        }
      }
      allSendResults.push(...ccSendResults);
      const ccAllSuccess = ccSendResults.every((r) => r.success);
      const ccErrors = ccSendResults.filter((r) => !r.success).map((r) => r.error).filter(Boolean).join("; ");
      const ccLogStatus = ccAllSuccess ? "sent" : (ccSendResults.some((r) => r.success) ? "partial_failure" : "error");
      childStatusMap[ccMetaKey] = ccLogStatus;
      await logEmail(
        "morning_brief",
        ccSubjectText,
        CC_RECIPIENTS,
        ccHtmlBody,
        ccLogStatus,
        ccAllSuccess ? undefined : (ccErrors || "Send failed"),
        undefined,
        { child: ccMetaKey },
      );
    }

    const allSuccess = allSendResults.every((r) => r.success);

    logAudit("morning-weather-email", {
      category: "automation",
      event_type: "morning_brief",
      severity: "info",
      actor_id: "system",
      actor_name: "Cron",
      channel: "cron",
      summary: `Morning brief: ${allSendResults.length} emails attempted — ${Object.entries(childStatusMap).map(([k, v]) => `${k}: ${v}`).join(", ")}`,
      status: allSuccess ? "success" : "partial",
    });

    return res.json({ success: allSuccess, results: allSendResults });
  } catch (e) {
    console.error("Morning brief error:", e);
    logAudit("morning-weather-email", {
      category: "automation",
      event_type: "morning_brief_error",
      severity: "error",
      actor_id: "system",
      channel: "cron",
      summary: `Morning brief error: ${e instanceof Error ? e.message : "Unknown"}`,
      status: "error",
    });
    await enqueueFailedJob("morning-weather-email", e);

    try {
      await sendWhatsApp(
        `⚠️ Morning brief failed: ${e instanceof Error ? e.message : "Unknown error"}`,
      );
    } catch (_) {}

    return res.status(500).json({
      error: e instanceof Error ? e.message : "Unknown error",
    });
  }
});

export default router;
