// Shared pending-release publisher used by both the post-merge standalone
// script (scripts/publish-release.ts) and the in-server cron route
// (server/routes/updates-autogen.ts).
//
// Accepts a raw pg.PoolClient so it works in both contexts (the standalone
// script creates its own pool; the server reuses the shared app pool).
//
// Idempotency and race-safety:
//   - Each ship event carries a unique `shipId` UUID in PENDING.json,
//     generated by the task author. The shipId is the idempotency key —
//     NOT a content hash — so identical note text in later ships still
//     correctly creates a new version.
//   - All DB work (shipId check + INSERT rows + config upsert) happens
//     inside a single transaction that first acquires a session-level
//     Postgres advisory lock (pg_advisory_lock / pg_advisory_unlock).
//     This means concurrent executions (e.g. cron firing while post-merge
//     script is still running) cannot both see "not yet published" and
//     double-insert rows.

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { randomUUID } from "crypto";
import type pg from "pg";

const PENDING_FILE = resolve("pending-release/PENDING.json");
const SHIP_ID_KEY = "pending_release_ship_id";
const VALID_TYPES = new Set(["feature", "improvement", "fix"]);

// Stable integer lock key derived from the feature name using a well-known
// hash. pg_advisory_lock takes a bigint; we pick a fixed value here so all
// processes target the same lock.
const ADVISORY_LOCK_KEY = 7392847291; // arbitrary stable key for pending-release

export interface PendingEntry {
  title: string;
  description: string[];
  type: string;
}

export interface PendingData {
  shipId?: string;
  pending: unknown[];
}

export interface PublishResult {
  published: boolean;
  reason?: string;
  version?: string;
  ids?: string[];
  shipId?: string;
  entriesCount?: number;
}

export function loadPendingData(): PendingData | null {
  try {
    const raw = readFileSync(PENDING_FILE, "utf-8");
    return JSON.parse(raw) as PendingData;
  } catch {
    return null;
  }
}

export function sanitizeEntries(entries: unknown[]): PendingEntry[] {
  const out: PendingEntry[] = [];
  for (const raw of entries) {
    const e = raw as Record<string, unknown>;
    const title = String(e?.title ?? "").trim().slice(0, 120);
    if (!title) continue;

    let description: string[] = [];
    if (Array.isArray(e?.description)) {
      description = (e.description as unknown[])
        .map((b) => String(b).trim())
        .filter(Boolean)
        .slice(0, 4)
        .map((b) => b.slice(0, 200));
    }

    const rawType = String(e?.type ?? "").toLowerCase();
    const type = VALID_TYPES.has(rawType) ? rawType : "improvement";
    out.push({ title, description, type });
  }
  return out;
}

export function bumpVersion(latest: string | undefined, hasFeature: boolean): string {
  const m = latest?.match(/(\d+)\.(\d+)\.(\d+)/);
  if (!m) return "v1.0.0";
  const maj = Number(m[1]);
  let min = Number(m[2]);
  let pat = Number(m[3]);
  if (hasFeature) { min += 1; pat = 0; } else { pat += 1; }
  return `v${maj}.${min}.${pat}`;
}

/**
 * Publish any pending release notes atomically. All callers (post-merge
 * script, cron route, manual trigger) go through this function, which ensures
 * identical behaviour and race-safe idempotency via a Postgres advisory lock.
 *
 * @param client A pg.PoolClient from the caller's pool. The caller retains
 *               ownership; this function does NOT release the client.
 * @param trigger Short label written into the audit log ("post-merge", "cron", etc.)
 * @param t0      Unix-ms start time for duration_ms in the audit row.
 */
export async function publishPendingRelease(
  client: pg.PoolClient,
  trigger = "manual",
  t0 = Date.now(),
): Promise<PublishResult> {
  // 1. Load and validate the pending file.
  const data = loadPendingData();
  if (!data) {
    return { published: false, reason: "PENDING.json missing or unreadable" };
  }

  const rawEntries: unknown[] = Array.isArray(data?.pending) ? data.pending : [];
  const entries = sanitizeEntries(rawEntries);

  if (entries.length === 0) {
    return { published: false, reason: "no pending notes" };
  }

  // Auto-generate shipId if the file predates the convention.
  const shipId = data.shipId?.trim() || randomUUID();

  // 2. Acquire a session-level advisory lock before reading or writing any
  //    state, so concurrent invocations queue up rather than racing.
  //    pg_advisory_lock blocks until the lock is available; this is safe
  //    because both callers always release (see finally block below).
  await client.query("SELECT pg_advisory_lock($1)", [ADVISORY_LOCK_KEY]);

  try {
    // 3. Under the lock: re-check the idempotency state.
    const { rows: configRows } = await client.query<{ value: string }>(
      "SELECT value FROM system_configs WHERE key = $1",
      [SHIP_ID_KEY]
    );
    if (configRows[0]?.value === shipId) {
      return { published: false, reason: "already published", shipId };
    }

    // 4. Get the latest version for the bump calculation.
    const { rows: updateRows } = await client.query<{ version: string }>(
      "SELECT version FROM system_updates ORDER BY published_at DESC LIMIT 1"
    );
    const latestVersion = updateRows[0]?.version;
    const hasFeature = entries.some((e) => e.type === "feature");
    const version = bumpVersion(latestVersion, hasFeature);

    // 5. Publish atomically in a single transaction: rows + config (shipId).
    await client.query("BEGIN");

    const now = Date.now();
    const ids: string[] = [];
    for (let i = 0; i < entries.length; i++) {
      const e = entries[i];
      const bullets = e.description.map((b) => `- ${b}`).join("\n");
      const { rows } = await client.query<{ id: string }>(
        `INSERT INTO system_updates (title, description, version, update_type, published_at)
         VALUES ($1, $2, $3, $4, $5) RETURNING id`,
        [e.title, bullets, version, e.type, new Date(now - i * 1000)]
      );
      ids.push(rows[0].id);
    }

    await client.query(
      `INSERT INTO system_configs (key, value, description, updated_at)
       VALUES ($1, $2, $3, NOW())
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()`,
      [SHIP_ID_KEY, shipId, "shipId of the last ship event published by pending-release publisher"]
    );

    await client.query(
      `INSERT INTO system_audit_log
         (category, event_type, severity, actor_id, channel, summary, detail, status, duration_ms)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
      [
        "automation",
        "updates_autogen_run",
        "info",
        "system",
        trigger,
        `Published ${entries.length} What's New ${entries.length === 1 ? "entry" : "entries"} (${version})`,
        JSON.stringify({
          version,
          shipId,
          entries: entries.map((e) => ({ title: e.title, type: e.type })),
          ids,
          trigger,
        }),
        "success",
        Date.now() - t0,
      ]
    );

    await client.query("COMMIT");

    // 6. Clear the pending entries. Keep the shipId so the next task knows to
    //    replace it with a fresh UUID when adding new notes.
    try {
      writeFileSync(
        PENDING_FILE,
        JSON.stringify({ shipId, pending: [] }, null, 2) + "\n"
      );
    } catch (writeErr) {
      // Non-fatal: shipId idempotency prevents re-publishing even if the
      // file isn't cleared. Log and continue.
      console.warn(`[pending-release] Could not clear PENDING.json: ${writeErr}`);
    }

    return { published: true, version, ids, shipId, entriesCount: entries.length };
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    // Always release the advisory lock so other waiters can proceed.
    await client.query("SELECT pg_advisory_unlock($1)", [ADVISORY_LOCK_KEY]).catch(() => {});
  }
}
